server:
  port: 8080

spring:
  application:
    name: assignment
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      username: ${SPRING_REDIS_USERNAME}
      password: ${SPRING_REDIS_PASSWORD}
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
#    default-schema:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

cinemetrics:
  data:
    csv:
      academy-award-path: db/data/academy_awards.csv
  cache:
    expiration-in-minutes: 60
  client:
    omdbapi:
      base-url: http://www.omdbapi.com
      api-key: ENC(WtJFsHx3BTobZAu8V3PDT7ynWBseQcna)
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080
  jwt:
    secret: ENC(G8EMZFYZuTNzuhCmHMAMDBFnwwQDW6VuLsGaWGFokmmqGcRpeBnZkbyBh7l2CFJR9PvDa+u5UpBowzfDVkLcbFWr8BZTRr6lIl8HcBdwRNw=)
    expiration-in-milliseconds: 600000
  env:
    jasypt-encryptor-password: ${JASYPT_ENCRYPTOR_PASSWORD}
