server:
  port: 8080

spring:
  application:
    name: assignment
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
#    default-schema:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/cinemetrics
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

cinemetrics:
  data:
    csv:
      academy-award-path: db/data/academy_awards.csv
  cache:
    expiration-in-minutes: 60
  client:
    omdbapi:
      base-url: http://www.omdbapi.com
      api-key: ENC(UEdk0nPfbYJNozHC2VyPHjnfp2S+DGCl)
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080
  jwt:
    secret: ENC(piKfYmhWClAPtJrkV+1KZ+y/d6Fs9UovXIXcjt+ZLlSEy0nEcIfhYWhdeXKxVWavfDQWxPVme3N9vbU7d6oNeHfHJyAE/GcYxqYlTHyHHXg=)
    expiration-in-milliseconds: 600000
  env:
    jasypt-encryptor-password: jasypt-itest
