server:
  port: 8080

spring:
  application:
    name: assignment
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

cinemetrics:
  data:
    csv:
      academy-award-path: db/data/academy_awards.csv
  client:
    omdbapi:
      base-url: http://www.omdbapi.com
      api-key: ENC(WtJFsHx3BTobZAu8V3PDT7ynWBseQcna)
