@startuml
title user login jounrney

actor User
participant "AuthController" as Controller
participant "AuthService" as Service
participant "UserService" as UserService
participant "PasswordEncoder" as PasswordEncoder
participant "UserRepository" as Repo
participant "JwtTokenProvider" as JWT

User -> Controller: POST /api/v1/login\n{username, password}
Controller -> Service: authenticateAndGenerateToken\n(username, password)
Service -> UserService: isUserCredentialValid(username, password)
UserService -> Repo: findByName(username)
Repo --> UserService: User entity

UserService -> PasswordEncoder: matches(rawPassword, encodedPassword)
PasswordEncoder --> UserService: boolean result

UserService --> Service: isValid (true/false)
Service -> JWT: generateToken(user)
JWT --> Service: JWT token
Service --> Controller: token
Controller -> User: 200 OK\n{token}
@enduml
